server {
    listen 80;
    listen [::]:80;
    root /usr/share/nginx/html;
    server_name _;

    location / {
        index entry.html;
        try_files $uri /index.html;
        }

    include /etc/nginx/mime.types; # handle mime.
}
